### ISSUE TITLE
Dagster - Asset Check Partition Asset

### ISSUE THREAD

**Issue by culpgrant** [culpgrant/strava_mds#48]
The asset check:
```
 - asset: raw_ingest_strava_athlete_activities
    engine: polars
    tests:
      - name: not_null
        columns:
          - ID
      - name: unique
        columns:
          - ID
```
is not working on a partitioned asset. Might need to grab most recent partition, for what the run was requested for?
So If we are running it on partitions 2/3/2024 - 2/5/2024 then do that. I am sure dagster has some docs on this. But we are doing the factory approach.
